export default [
 {
   "id": 131,
   "className": "Community Class",
   "studio": "Shambhala Yoga and Dance Center",
   "coords": "40.6774267,-73.9648663",
   "borough": "brooklyn",
   "neighborhood": "Prospect Heights",
   "day": "wednesday",
   "classStart": "6:00",
   "classEnd": "6:45",
   "teacher": "Sarah Fishstrom",
   "price": null,
   "scheduleLink": "http://shambhalayogadance.com/schedule/"
 },
 {
   "id": 161,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053711",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "6:30",
   "classEnd": "8:00",
   "teacher": "Alina Yuen",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 162,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053712",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "tuesday",
   "classStart": "6:30",
   "classEnd": "8:00",
   "teacher": "Alina Yuen",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 163,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053713",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "6:30",
   "classEnd": "8:00",
   "teacher": "Jacqueline Montenegro",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 164,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053714",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "6:30",
   "classEnd": "8:00",
   "teacher": "Jacqueline Montenegro",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 63,
   "className": "All Levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "monday",
   "classStart": "6:45",
   "classEnd": "7:45",
   "teacher": "Netchem Hairston",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "id": 93,
   "className": "Donation-Based Class - Asana/Meditation",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "monday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 94,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "tuesday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "Andrea",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 95,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "wednesday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "Erica",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 96,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "Andrea",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 97,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "friday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "Erica",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 129,
   "className": "Varies",
   "studio": "Brooklyn Yoga Collective",
   "coords": "40.671702,-73.9594637",
   "borough": "brooklyn",
   "neighborhood": "Crown Heights",
   "day": "monday - sunday",
   "classStart": "7:00",
   "classEnd": "22:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://brooklynyogacollective.com/#calendar_anchor"
 },
 {
   "id": 145,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 146,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "tuesday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 147,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 148,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 149,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 165,
   "className": "Yang/Yin ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053715",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "7:00",
   "classEnd": "8:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 72,
   "className": "Win Win Donation Class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "monday",
   "classStart": "7:30",
   "classEnd": "8:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "id": 73,
   "className": "Win Win Donation Class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "7:30",
   "classEnd": "8:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "id": 87,
   "className": "Morning Meditation with Open Sky Sangha",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "tuesday",
   "classStart": "8:00",
   "classEnd": "9:00",
   "teacher": "Giorgio Handman",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "id": 89,
   "className": "Morning Meditation with Open Sky Sangha",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "8:00",
   "classEnd": "9:00",
   "teacher": "Giorgio Handman",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "id": 157,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "saturday",
   "classStart": "8:00",
   "classEnd": "9:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 158,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "sunday",
   "classStart": "8:00",
   "classEnd": "9:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 62,
   "className": "All Levels Community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "sunday",
   "classStart": "8:15",
   "classEnd": "9:15",
   "teacher": "Kristin Law",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "id": 30,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7089307,-73.9625562",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "9:00",
   "classEnd": "10:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 31,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7089307,-73.9625562",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "thursday",
   "classStart": "9:00",
   "classEnd": "10:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 134,
   "className": "Varies ($10 min donation)",
   "studio": "Brooklyn Yoga School",
   "coords": "40.6798509,-73.9773543",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "monday - sunday",
   "classStart": "9:00",
   "classEnd": "22:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.brooklynyogaschool.com/schedule/"
 },
 {
   "id": 140,
   "className": "Rising Teacher's Yoga",
   "studio": "Third Root Community Health Center",
   "coords": "40.6413573,-73.9652507",
   "borough": "brooklyn",
   "neighborhood": "Kensington",
   "day": "thursday",
   "classStart": "9:00",
   "classEnd": "10:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.secure-booker.com/thirdroot/ClassSchedule/ClassSchedule.aspx#"
 },
 {
   "id": 53,
   "className": "Integral Level 1 Community Class",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "9:15",
   "classEnd": "10:45",
   "teacher": "Gabriella",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "id": 135,
   "className": "Open Flow-Pay What You Can",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "wednesday",
   "classStart": "9:15",
   "classEnd": "10:30",
   "teacher": "Amy Quinn Suplina",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "id": 34,
   "className": "YIN Flow Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "tuesday",
   "classStart": "9:30",
   "classEnd": "10:30",
   "teacher": "Robert Foerster",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 37,
   "className": "YIN Flow Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "9:30",
   "classEnd": "10:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 166,
   "className": "Hot Vinyasa ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053717",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "9:30",
   "classEnd": "10:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 66,
   "className": "All Levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "sunday",
   "classStart": "10:00",
   "classEnd": "11:00",
   "teacher": "Syama Masla",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "id": 86,
   "className": "Community Yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "monday",
   "classStart": "10:00",
   "classEnd": "11:30",
   "teacher": "Caitlyn Johansen",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "id": 113,
   "className": "Advanced Flow (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "friday",
   "classStart": "10:00",
   "classEnd": "11:15",
   "teacher": "Ge Wang",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 115,
   "className": "All Level Flow (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "sunday",
   "classStart": "10:00",
   "classEnd": "11:30",
   "teacher": "Jessica Lum",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 128,
   "className": "COMMUNITY Open Level",
   "studio": "Ridgewood Yoga Studio",
   "coords": "40.6978022,-73.9084293",
   "borough": "queens",
   "neighborhood": "Ridgewood",
   "day": "thursday",
   "classStart": "10:00",
   "classEnd": "11:00",
   "teacher": "Nyota Nayo",
   "price": null,
   "scheduleLink": "http://ridgewoodyogastudio.com/"
 },
 {
   "id": 75,
   "className": "Win Win Donation Class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "sunday",
   "classStart": "10:15",
   "classEnd": "11:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "id": 8,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "tuesday",
   "classStart": "11:00",
   "classEnd": "12:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 11,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "wednesday",
   "classStart": "11:00",
   "classEnd": "12:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 13,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "thursday",
   "classStart": "11:00",
   "classEnd": "12:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 122,
   "className": "Donation Meditation",
   "studio": "Makara Studio",
   "coords": "40.7072587,-73.9450777",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "11:00",
   "classEnd": "23:45",
   "teacher": "Conni Mallchock",
   "price": null,
   "scheduleLink": "http://makarastudio.com/classes"
 },
 {
   "id": 139,
   "className": "Open By Donation",
   "studio": "Third Root Community Health Center",
   "coords": "40.6413573,-73.9652507",
   "borough": "brooklyn",
   "neighborhood": "Kensington",
   "day": "wednesday",
   "classStart": "11:15",
   "classEnd": "12:30",
   "teacher": "Shelly Nicole",
   "price": null,
   "scheduleLink": "http://www.secure-booker.com/thirdroot/ClassSchedule/ClassSchedule.aspx#"
 },
 {
   "id": 68,
   "className": "Mindful Yoga for Veterans (and everyone)",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "saturday",
   "classStart": "11:30",
   "classEnd": "13:00",
   "teacher": "Madelaine Mayer",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "id": 69,
   "className": "Community Yoga",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "sunday",
   "classStart": "11:30",
   "classEnd": "12:45",
   "teacher": "Stephen McManus",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "id": 116,
   "className": "Lunchtime Meditation",
   "studio": "Sangha Yoga Shala",
   "coords": "40.716954,-73.9639786",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "11:30",
   "classEnd": "12:00",
   "teacher": "Alana Kessler",
   "price": null,
   "scheduleLink": "http://sanghayoganyc.com/yoga/"
 },
 {
   "id": 64,
   "className": "All Levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "tuesday",
   "classStart": "12:00",
   "classEnd": "13:00",
   "teacher": "Ira Ruiz",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "id": 65,
   "className": "All Levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "thursday",
   "classStart": "12:00",
   "classEnd": "13:00",
   "teacher": "Dhyana Masla",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "id": 90,
   "className": "Community Yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "12:00",
   "classEnd": "13:15",
   "teacher": "Madeline Warriner",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "id": 156,
   "className": "Inversions Flow Level 3 ($10)",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "saturday",
   "classStart": "12:00",
   "classEnd": "13:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 159,
   "className": "Vinyasa Level 3 ($10)",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "sunday",
   "classStart": "12:00",
   "classEnd": "13:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 167,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053718",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "12:00",
   "classEnd": "13:30",
   "teacher": "Chris Olstrom",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 40,
   "className": "Community Class",
   "studio": "Yoga Shanti",
   "coords": "40.7431682,-73.9939468",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "sunday",
   "classStart": "12:15",
   "classEnd": "13:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://yogashanti.com/new-york-city/#schedule"
 },
 {
   "id": 111,
   "className": "All Level Flow (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "thursday",
   "classStart": "12:15",
   "classEnd": "13:20",
   "teacher": "Stefanie Mihoulides",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 117,
   "className": "Lunchtime Meditation",
   "studio": "Sangha Yoga Shala",
   "coords": "40.716954,-73.9639786",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "12:30",
   "classEnd": "13:15",
   "teacher": "Alana Kessler",
   "price": null,
   "scheduleLink": "http://sanghayoganyc.com/yoga/"
 },
 {
   "id": 136,
   "className": "Hour Basics-Pay What You Can",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "thursday",
   "classStart": "12:30",
   "classEnd": "13:30",
   "teacher": "Cari Friedman",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "id": 137,
   "className": "Hour Basics-Pay What You Can",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "thursday",
   "classStart": "12:30",
   "classEnd": "13:30",
   "teacher": "Cari Friedman",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "id": 141,
   "className": "Open By Donation",
   "studio": "Third Root Community Health Center",
   "coords": "40.6413573,-73.9652507",
   "borough": "brooklyn",
   "neighborhood": "Kensington",
   "day": "saturday",
   "classStart": "12:30",
   "classEnd": "13:45",
   "teacher": "Elizabeth Gonzalez",
   "price": null,
   "scheduleLink": "http://www.secure-booker.com/thirdroot/ClassSchedule/ClassSchedule.aspx#"
 },
 {
   "id": 32,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7089307,-73.9625562",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "13:00",
   "classEnd": "14:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 85,
   "className": "CC Hot Power (Open)",
   "studio": "Pure Yoga West",
   "coords": "40.781852,-73.9819977",
   "borough": "manhattan",
   "neighborhood": "Upper West Side",
   "day": "sunday",
   "classStart": "13:00",
   "classEnd": "14:00",
   "teacher": "Holly Corey",
   "price": null,
   "scheduleLink": "http://pureyoga.com/apps/mindbody/elements/listschedule.php"
 },
 {
   "id": 98,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "monday",
   "classStart": "13:00",
   "classEnd": "14:00",
   "teacher": "Kelley",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 99,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "tuesday",
   "classStart": "13:00",
   "classEnd": "14:00",
   "teacher": "Carole",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 100,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "wednesday",
   "classStart": "13:00",
   "classEnd": "14:00",
   "teacher": "Kelley",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 101,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "13:00",
   "classEnd": "14:00",
   "teacher": "Juan",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 102,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "friday",
   "classStart": "13:00",
   "classEnd": "14:00",
   "teacher": "Carole",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 57,
   "className": "Free Integral Intro Class (drop-in)",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "sunday",
   "classStart": "13:15",
   "classEnd": "15:00",
   "teacher": "Margaret Padma",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "id": 123,
   "className": "Donation Yoga Open Level",
   "studio": "Makara Studio",
   "coords": "40.7072587,-73.9450777",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "13:15",
   "classEnd": "14:45",
   "teacher": "Lola",
   "price": null,
   "scheduleLink": "http://makarastudio.com/classes"
 },
 {
   "id": 26,
   "className": "Donation-Based Open Flow",
   "studio": "Sacred Sounds",
   "coords": "40.7287866,-74.0021453",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "monday",
   "classStart": "13:30",
   "classEnd": "14:45",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.sacredsoundsyoga.com/classes/class-schedule-sign-up/"
 },
 {
   "id": 27,
   "className": "Donation-Based Open Flow",
   "studio": "Sacred Sounds",
   "coords": "40.7287866,-74.0021453",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "wednesday",
   "classStart": "13:30",
   "classEnd": "14:45",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.sacredsoundsyoga.com/classes/class-schedule-sign-up/"
 },
 {
   "id": 28,
   "className": "Donation-Based Open Flow",
   "studio": "Sacred Sounds",
   "coords": "40.7287866,-74.0021453",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "friday",
   "classStart": "13:30",
   "classEnd": "14:45",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.sacredsoundsyoga.com/classes/class-schedule-sign-up/"
 },
 {
   "id": 77,
   "className": "30 Minute Meditation Free",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "monday",
   "classStart": "13:30",
   "classEnd": "14:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "id": 108,
   "className": "Meditation (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "tuesday",
   "classStart": "13:30",
   "classEnd": "14:00",
   "teacher": "Stefanie Mihoulides",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 112,
   "className": "Meditation (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "thursday",
   "classStart": "13:30",
   "classEnd": "14:00",
   "teacher": "Stefanie Mihoulides",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 142,
   "className": "Vinyasa Flow ($10)",
   "studio": "The Yoga Room",
   "coords": "40.7397922,-73.9358425",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "13:30",
   "classEnd": "14:45",
   "teacher": "Ellen",
   "price": null,
   "scheduleLink": "http://www.the-yoga-room.com/classes/yoga-classes/"
 },
 {
   "id": 143,
   "className": "Vinyasa Flow ($10)",
   "studio": "The Yoga Room",
   "coords": "40.7397922,-73.9358425",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "13:30",
   "classEnd": "14:30",
   "teacher": "Lauren",
   "price": null,
   "scheduleLink": "http://www.the-yoga-room.com/classes/yoga-classes/"
 },
 {
   "id": 130,
   "className": "Community Class",
   "studio": "Shambhala Yoga and Dance Center",
   "coords": "40.6774267,-73.9648663",
   "borough": "brooklyn",
   "neighborhood": "Prospect Heights",
   "day": "tuesday",
   "classStart": "13:45",
   "classEnd": "14:45",
   "teacher": "Sabine Jean-François",
   "price": null,
   "scheduleLink": "http://shambhalayogadance.com/schedule/"
 },
 {
   "id": 132,
   "className": "Community Class",
   "studio": "Shambhala Yoga and Dance Center",
   "coords": "40.6774267,-73.9648663",
   "borough": "brooklyn",
   "neighborhood": "Prospect Heights",
   "day": "thursday",
   "classStart": "13:45",
   "classEnd": "14:45",
   "teacher": "Shawna Wakefield",
   "price": null,
   "scheduleLink": "http://shambhalayogadance.com/schedule/"
 },
 {
   "id": 6,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "monday",
   "classStart": "14:00",
   "classEnd": "15:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 9,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "tuesday",
   "classStart": "14:00",
   "classEnd": "15:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 12,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "wednesday",
   "classStart": "14:00",
   "classEnd": "15:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 14,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "thursday",
   "classStart": "14:00",
   "classEnd": "15:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 16,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "friday",
   "classStart": "14:00",
   "classEnd": "15:05",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 22,
   "className": "Flow & Meditate (Community)",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "thursday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "Monica Perry",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 41,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256355,-73.9895042",
   "borough": "manhattan",
   "neighborhood": "West Village",
   "day": "monday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 42,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256355,-73.9895042",
   "borough": "manhattan",
   "neighborhood": "West Village",
   "day": "tuesday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 43,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256355,-73.9895042",
   "borough": "manhattan",
   "neighborhood": "West Village",
   "day": "wednesday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 44,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "monday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 45,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 46,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "wednesday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 47,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "thursday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 48,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "friday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 49,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 50,
   "className": "Modo Love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "id": 82,
   "className": "Slow Flow Community Class",
   "studio": "House of Jai",
   "coords": "40.7701017,-73.9561812",
   "borough": "manhattan",
   "neighborhood": "Upper East Side",
   "day": "saturday",
   "classStart": "14:00",
   "classEnd": "15:15",
   "teacher": "Serra Saridereli",
   "price": null,
   "scheduleLink": "http://www.houseofjai.com/schedule.php"
 },
 {
   "id": 83,
   "className": "CC Hot Vinyasa",
   "studio": "Pure Yoga West",
   "coords": "40.781852,-73.9819977",
   "borough": "manhattan",
   "neighborhood": "Upper West Side",
   "day": "thursday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "Matt Goldmark",
   "price": null,
   "scheduleLink": "http://pureyoga.com/apps/mindbody/elements/listschedule.php"
 },
 {
   "id": 103,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "saturday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "Juan",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 104,
   "className": "Donation-Based Class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "sunday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "Carole",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 114,
   "className": "Advanced Flow (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "saturday",
   "classStart": "14:00",
   "classEnd": "15:15",
   "teacher": "Michael Santaniello",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 124,
   "className": "Donation Yoga Open Level",
   "studio": "Makara Studio",
   "coords": "40.7072587,-73.9450777",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "14:00",
   "classEnd": "15:15",
   "teacher": "Leyla",
   "price": null,
   "scheduleLink": "http://makarastudio.com/classes"
 },
 {
   "id": 125,
   "className": "Community Class ($5)",
   "studio": "Daya Yoga Studio",
   "coords": "40.705452,-73.9269326",
   "borough": "brooklyn",
   "neighborhood": "Bushwick",
   "day": "tuesdat",
   "classStart": "14:00",
   "classEnd": "15:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://dayayogastudio.com/"
 },
 {
   "id": 127,
   "className": "Community Class ($5)",
   "studio": "Daya Yoga Studio",
   "coords": "40.705452,-73.9269326",
   "borough": "brooklyn",
   "neighborhood": "Bushwick",
   "day": "thursday",
   "classStart": "14:00",
   "classEnd": "15:15",
   "teacher": "Michelle Miller",
   "price": null,
   "scheduleLink": "http://dayayogastudio.com/"
 },
 {
   "id": 150,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 151,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "tuesday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 152,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 153,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 154,
   "className": "Open Level Vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "14:00",
   "classEnd": "15:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 23,
   "className": "Aerial Yoga Core: Open Level (Community)",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "friday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 33,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "monday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 35,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "tuesday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 36,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 38,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 39,
   "className": "Community Class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "friday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "id": 52,
   "className": "Yoga for the Unemployed",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "Nalini Kuhnke",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "id": 74,
   "className": "Win Win Donation Class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "14:30",
   "classEnd": "15:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "id": 84,
   "className": "CC Hot Slow Flow",
   "studio": "Pure Yoga East",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Upper East Side",
   "day": "thursday",
   "classStart": "14:30",
   "classEnd": "15:00",
   "teacher": "Irina Baysara",
   "price": null,
   "scheduleLink": "http://pureyoga.com/apps/mindbody/elements/listschedule.php"
 },
 {
   "id": 58,
   "className": "All Levels Community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "monday",
   "classStart": "15:00",
   "classEnd": "16:00",
   "teacher": "Michele Vindigni",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "id": 59,
   "className": "All Levels Community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "tuesday",
   "classStart": "15:00",
   "classEnd": "16:00",
   "teacher": "Sky Spallone",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "id": 60,
   "className": "All Levels Community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "wednesday",
   "classStart": "15:00",
   "classEnd": "16:00",
   "teacher": "Amanda Shafran",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "id": 61,
   "className": "All Levels Community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "friday",
   "classStart": "15:00",
   "classEnd": "16:00",
   "teacher": "Susan Ingraham",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "id": 78,
   "className": "Donation Community Class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "monday",
   "classStart": "15:00",
   "classEnd": "16:00",
   "teacher": "Michelle Vanegas",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "id": 79,
   "className": "Donation Community Class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "wednesday",
   "classStart": "15:00",
   "classEnd": "16:00",
   "teacher": "Amanda Reichert",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "id": 81,
   "className": "Donation Community Class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "sunday",
   "classStart": "15:00",
   "classEnd": "16:00",
   "teacher": "Lee Ann Walton",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "id": 92,
   "className": "Community Yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "sunday",
   "classStart": "15:30",
   "classEnd": "16:30",
   "teacher": "Lauren Solomon",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "id": 144,
   "className": "Vinyasa Flow ($10)",
   "studio": "The Yoga Room",
   "coords": "40.7397922,-73.9358425",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "saturday",
   "classStart": "15:30",
   "classEnd": "16:45",
   "teacher": "Amanda",
   "price": null,
   "scheduleLink": "http://www.the-yoga-room.com/classes/yoga-classes/"
 },
 {
   "id": 18,
   "className": "Vinyasa (Community): Open Level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "monday",
   "classStart": "16:00",
   "classEnd": "17:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 20,
   "className": "Vinyasa (Community): Open Level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "wednesday",
   "classStart": "16:00",
   "classEnd": "17:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 29,
   "className": "Community Class",
   "studio": "Kula Yoga",
   "coords": "40.7172774,-73.9646361",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "16:00",
   "classEnd": "17:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://kulayoga.com/studios/"
 },
 {
   "id": 67,
   "className": "Liberation Prison Yoga Community Class",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "monday",
   "classStart": "16:00",
   "classEnd": "17:00",
   "teacher": "Onieka Mays",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "id": 105,
   "className": "Donation-Based Class - Beginners",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "saturday",
   "classStart": "16:00",
   "classEnd": "17:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 106,
   "className": "Donation-Based Class - Beginners",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "sunday",
   "classStart": "16:00",
   "classEnd": "17:00",
   "teacher": "Luis",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "id": 118,
   "className": "Community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "monday",
   "classStart": "16:00",
   "classEnd": "17:30",
   "teacher": "Salvador",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "id": 119,
   "className": "Community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "16:00",
   "classEnd": "17:30",
   "teacher": "Gabe",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "id": 120,
   "className": "Community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "thursday",
   "classStart": "16:00",
   "classEnd": "17:30",
   "teacher": "Sabina",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "id": 121,
   "className": "Community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "friday",
   "classStart": "16:00",
   "classEnd": "17:30",
   "teacher": "Kirby",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "id": 168,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053719",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "16:30",
   "classEnd": "18:00",
   "teacher": "Frank King",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 55,
   "className": "Free Deep Relaxation",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "friday",
   "classStart": "17:00",
   "classEnd": "17:45",
   "teacher": "Craig Carlson",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "id": 70,
   "className": "Yoga for 12 Step Recovery",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "sunday",
   "classStart": "17:00",
   "classEnd": "18:30",
   "teacher": "Adina Saperstein",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "id": 138,
   "className": "Hour Align-Pay What You Can ",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "friday",
   "classStart": "17:00",
   "classEnd": "18:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "id": 88,
   "className": "Community Yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "wednesday",
   "classStart": "17:45",
   "classEnd": "18:45",
   "teacher": "Matty Espino",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "id": 25,
   "className": "Vinyasa (Community): Open Level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "sunday",
   "classStart": "18:00",
   "classEnd": "19:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 76,
   "className": "Community Class",
   "studio": "Mang'Oh Yoga",
   "coords": "40.747274,-73.9748507",
   "borough": "manhattan",
   "neighborhood": "Murray Hill",
   "day": "sunday",
   "classStart": "18:00",
   "classEnd": "19:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.mangohstudio.com/"
 },
 {
   "id": 5,
   "className": "Now:Yoga Community",
   "studio": "The Shala",
   "coords": "40.6575012,-74.0464639",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "wednesday",
   "classStart": "18:15",
   "classEnd": "19:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://theshala.com/"
 },
 {
   "id": 51,
   "className": "Level 2/3 Community Class",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "tuesday",
   "classStart": "18:15",
   "classEnd": "19:45",
   "teacher": "Anamaya",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "id": 56,
   "className": "Integral Level 1 Community Class",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "saturday",
   "classStart": "18:15",
   "classEnd": "19:45",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "id": 24,
   "className": "Vinyasa (Community): Open Level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "saturday",
   "classStart": "18:30",
   "classEnd": "19:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 107,
   "className": "All Level Flow (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "monday",
   "classStart": "18:30",
   "classEnd": "19:45",
   "teacher": "Jen Devery",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 109,
   "className": "All Level Flow (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "tuesday",
   "classStart": "18:30",
   "classEnd": "19:45",
   "teacher": "Roque Rodriguez",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 169,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053720",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "18:30",
   "classEnd": "20:00",
   "teacher": "Joseph Encina",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 1,
   "className": "Community Flow & Restore",
   "studio": "YogaSole",
   "coords": "40.6575224,-73.9786126",
   "borough": "brooklyn",
   "neighborhood": "Windsor Terrace",
   "day": "thursday",
   "classStart": "19:00",
   "classEnd": "20:15",
   "teacher": "GianCarla",
   "price": "any donation",
   "scheduleLink": "http://yogasole.com/schedule.html"
 },
 {
   "id": 2,
   "className": "Community Flow",
   "studio": "YogaSole",
   "coords": "40.6575224,-73.9786126",
   "borough": "brooklyn",
   "neighborhood": "Windsor Terrace",
   "day": "friday",
   "classStart": "19:00",
   "classEnd": "20:00",
   "teacher": "TBD",
   "price": "any donation",
   "scheduleLink": "http://yogasole.com/schedule.html"
 },
 {
   "id": 54,
   "className": "Yoga for Veterans",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "19:00",
   "classEnd": "20:30",
   "teacher": "Anuradha Bhagwati",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "id": 71,
   "className": "Power Community $10",
   "studio": "Lyons Den Power Yoga",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Tribeca",
   "day": "sunday",
   "classStart": "19:00",
   "classEnd": "20:00",
   "teacher": "Aneta Bondarenko",
   "price": null,
   "scheduleLink": "http://lyonsdenpoweryoga.com/"
 },
 {
   "id": 7,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "monday",
   "classStart": "19:30",
   "classEnd": "20:35",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 10,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "tuesday",
   "classStart": "19:30",
   "classEnd": "20:35",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 15,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "thursday",
   "classStart": "19:30",
   "classEnd": "20:35",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 17,
   "className": "Community Class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "friday",
   "classStart": "19:30",
   "classEnd": "20:35",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "id": 110,
   "className": "All Level Flow (Donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "wednesday",
   "classStart": "20:00",
   "classEnd": "21:00",
   "teacher": "Julia Schonberg",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "id": 133,
   "className": "Community Class",
   "studio": "Area Yoga Brooklyn",
   "coords": "40.6815356,-73.9789979",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "sunday",
   "classStart": "20:15",
   "classEnd": "21:15",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.areayogabrooklyn.com/"
 },
 {
   "id": 170,
   "className": "Bikram's Yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053721",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "20:15",
   "classEnd": "21:45",
   "teacher": "Johanna Fausto",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "id": 3,
   "className": "All Levels / By Donation",
   "studio": "The Shala",
   "coords": "40.6575012,-74.0464639",
   "borough": "brooklyn",
   "neighborhood": "Fort Greene",
   "day": "monday",
   "classStart": "20:30",
   "classEnd": "21:45",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://theshala.com/"
 },
 {
   "id": 4,
   "className": "All Levels / By Donation",
   "studio": "The Shala",
   "coords": "40.6575012,-74.0464639",
   "borough": "brooklyn",
   "neighborhood": "Fort Greene",
   "day": "wednesday",
   "classStart": "20:30",
   "classEnd": "21:45",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://theshala.com/"
 },
 {
   "id": 19,
   "className": "Vinyasa (Community): Open Level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "monday",
   "classStart": "20:30",
   "classEnd": "21:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 21,
   "className": "Vinyasa (Community): Open Level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "wednesday",
   "classStart": "20:30",
   "classEnd": "21:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "id": 80,
   "className": "Donation Community Class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "wednesday",
   "classStart": "20:30",
   "classEnd": "21:30",
   "teacher": "Kiara Contreras",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "id": 155,
   "className": "Yin Yoga ($10)",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "20:30",
   "classEnd": "22:00",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 160,
   "className": "Meditation",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "sunday",
   "classStart": "20:30",
   "classEnd": "21:30",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "id": 126,
   "className": "Meditation (Donation)",
   "studio": "Daya Yoga Studio",
   "coords": "40.705452,-73.9269326",
   "borough": "brooklyn",
   "neighborhood": "Bushwick",
   "day": "wednesday",
   "classStart": "21:15",
   "classEnd": "9:45",
   "teacher": "Jen MacFarlane",
   "price": null,
   "scheduleLink": "http://dayayogastudio.com/"
 },
 {
   "id": 91,
   "className": "Community Prenatal",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "friday",
   "classStart": "22:45",
   "classEnd": "12:15",
   "teacher": "Nyota Nayo",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 }
]