export default [
 {
   "className": "community flow & restore",
   "studio": "YogaSole",
   "coords": "40.6575224,-73.9786126",
   "borough": "brooklyn",
   "neighborhood": "Windsor Terrace",
   "day": "thursday",
   "classStart": "7:00pm",
   "classEnd": "8:15pm",
   "teacher": "GianCarla",
   "price": "any donation",
   "scheduleLink": "http://yogasole.com/schedule.html"
 },
 {
   "className": "community flow",
   "studio": "YogaSole",
   "coords": "40.6575224,-73.9786126",
   "borough": "brooklyn",
   "neighborhood": "Windsor Terrace",
   "day": "friday",
   "classStart": "7:00pm",
   "classEnd": "8:00pm",
   "teacher": "TBD",
   "price": "any donation",
   "scheduleLink": "http://yogasole.com/schedule.html"
 },
 {
   "className": "all levels / by donation",
   "studio": "The Shala",
   "coords": "40.6575012,-74.0464639",
   "borough": "brooklyn",
   "neighborhood": "Fort Greene",
   "day": "monday",
   "classStart": "8:30pm",
   "classEnd": "9:45pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://theshala.com/"
 },
 {
   "className": "all levels / by donation",
   "studio": "The Shala",
   "coords": "40.6575012,-74.0464639",
   "borough": "brooklyn",
   "neighborhood": "Fort Greene",
   "day": "wednesday",
   "classStart": "8:30pm",
   "classEnd": "9:45pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://theshala.com/"
 },
 {
   "className": "now:yoga community",
   "studio": "The Shala",
   "coords": "40.6575012,-74.0464639",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "wednesday",
   "classStart": "6:15pm",
   "classEnd": "7:15pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://theshala.com/"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "monday",
   "classStart": "2:00pm",
   "classEnd": "3:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "monday",
   "classStart": "7:30pm",
   "classEnd": "8:35pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "tuesday",
   "classStart": "11:00am",
   "classEnd": "12:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "tuesday",
   "classStart": "2:00pm",
   "classEnd": "3:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "tuesday",
   "classStart": "7:30pm",
   "classEnd": "8:35pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "wednesday",
   "classStart": "11:00am",
   "classEnd": "12:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "wednesday",
   "classStart": "2:00pm",
   "classEnd": "3:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "thursday",
   "classStart": "11:00am",
   "classEnd": "12:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "thursday",
   "classStart": "2:00pm",
   "classEnd": "3:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "thursday",
   "classStart": "7:30pm",
   "classEnd": "8:35pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "friday",
   "classStart": "2:00pm",
   "classEnd": "3:05pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "community class",
   "studio": "Yoga Vida",
   "coords": "40.7269063,-73.9972694",
   "borough": "manhattan",
   "neighborhood": "NoHo",
   "day": "friday",
   "classStart": "7:30pm",
   "classEnd": "8:35pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://yogavida.com/pages/class-schedule"
 },
 {
   "className": "vinyasa (community): open level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "monday",
   "classStart": "4:00pm",
   "classEnd": "5:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "vinyasa (community): open level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "monday",
   "classStart": "8:30pm",
   "classEnd": "9:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "vinyasa (community): open level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "wednesday",
   "classStart": "4:00pm",
   "classEnd": "5:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "vinyasa (community): open level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "wednesday",
   "classStart": "8:30pm",
   "classEnd": "9:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "flow & meditate (community)",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "thursday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "Monica Perry",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "aerial yoga core: open level (community)",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "friday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "vinyasa (community): open level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "saturday",
   "classStart": "6:30pm",
   "classEnd": "7:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "vinyasa (community): open level",
   "studio": "Om Factory",
   "coords": "40.754149,-73.9937507",
   "borough": "manhattan",
   "neighborhood": "Fashion District",
   "day": "sunday",
   "classStart": "6:00pm",
   "classEnd": "7:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://www.omfactory.yoga/classes/fd-schedule/"
 },
 {
   "className": "donation-based open flow",
   "studio": "Sacred Sounds",
   "coords": "40.7287866,-74.0021453",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "monday",
   "classStart": "1:30pm",
   "classEnd": "2:45pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.sacredsoundsyoga.com/classes/class-schedule-sign-up/"
 },
 {
   "className": "donation-based open flow",
   "studio": "Sacred Sounds",
   "coords": "40.7287866,-74.0021453",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "wednesday",
   "classStart": "1:30pm",
   "classEnd": "2:45pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.sacredsoundsyoga.com/classes/class-schedule-sign-up/"
 },
 {
   "className": "donation-based open flow",
   "studio": "Sacred Sounds",
   "coords": "40.7287866,-74.0021453",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "friday",
   "classStart": "1:30pm",
   "classEnd": "2:45pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.sacredsoundsyoga.com/classes/class-schedule-sign-up/"
 },
 {
   "className": "community class",
   "studio": "Kula Yoga",
   "coords": "40.7172774,-73.9646361",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "4:00pm",
   "classEnd": "5:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://kulayoga.com/studios/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7089307,-73.9625562",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "9:00am",
   "classEnd": "10:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7089307,-73.9625562",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "thursday",
   "classStart": "9:00am",
   "classEnd": "10:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7089307,-73.9625562",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "1:00pm",
   "classEnd": "2:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "monday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "yin flow community class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "tuesday",
   "classStart": "9:30am",
   "classEnd": "10:30am",
   "teacher": "Robert Foerster",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "tuesday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "yin flow community class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "9:30am",
   "classEnd": "10:30am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Laughing Lotus",
   "coords": "40.7404323,-73.9962871",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "friday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.laughinglotus.com/classes/"
 },
 {
   "className": "community class",
   "studio": "Yoga Shanti",
   "coords": "40.7431682,-73.9939468",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "sunday",
   "classStart": "12:15",
   "classEnd": "1:15pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://yogashanti.com/new-york-city/#schedule"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256355,-73.9895042",
   "borough": "manhattan",
   "neighborhood": "West Village",
   "day": "monday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256355,-73.9895042",
   "borough": "manhattan",
   "neighborhood": "West Village",
   "day": "tuesday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256355,-73.9895042",
   "borough": "manhattan",
   "neighborhood": "West Village",
   "day": "wednesday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "monday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "wednesday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "thursday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "friday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "modo love",
   "studio": "Modo Yoga",
   "coords": "40.7256362,-73.9895042",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://nyc.modoyoga.com/classes/#schedule2"
 },
 {
   "className": "level 2/3 community class",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "tuesday",
   "classStart": "6:15pm",
   "classEnd": "7:45pm",
   "teacher": "Anamaya",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "className": "yoga for the unemployed",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "Nalini Kuhnke",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "className": "integral level 1 community class",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "9:15am",
   "classEnd": "10:45am",
   "teacher": "Gabriella",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "className": "yoga for veterans",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "thursday",
   "classStart": "7:00pm",
   "classEnd": "8:30pm",
   "teacher": "Anuradha Bhagwati",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "className": "free deep relaxation",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "friday",
   "classStart": "5:00pm",
   "classEnd": "5:45pm",
   "teacher": "Craig Carlson",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "className": "integral level 1 community class",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "saturday",
   "classStart": "6:15pm",
   "classEnd": "7:45pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "className": "free integral intro class (drop-in)",
   "studio": "Integral Yoga Institute",
   "coords": "40.7385097,-74.0036784",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "sunday",
   "classStart": "1:15pm",
   "classEnd": "3:00pm",
   "teacher": "Margaret Padma",
   "price": null,
   "scheduleLink": "http://iyiny.org/"
 },
 {
   "className": "all levels community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "monday",
   "classStart": "3:00pm",
   "classEnd": "4:00pm",
   "teacher": "Michele Vindigni",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "className": "all levels community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "tuesday",
   "classStart": "3:00pm",
   "classEnd": "4:00pm",
   "teacher": "Sky Spallone",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "className": "all levels community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "wednesday",
   "classStart": "3:00pm",
   "classEnd": "4:00pm",
   "teacher": "Amanda Shafran",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "className": "all levels community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "friday",
   "classStart": "3:00pm",
   "classEnd": "4:00pm",
   "teacher": "Susan Ingraham",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "className": "all levels community",
   "studio": "Ishta Yoga",
   "coords": "40.7327904,-73.9948367",
   "borough": "manhattan",
   "neighborhood": "Union Square",
   "day": "sunday",
   "classStart": "8:15am",
   "classEnd": "9:15am",
   "teacher": "Kristin Law",
   "price": null,
   "scheduleLink": "http://www.ishtayoga.com/"
 },
 {
   "className": "all levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "monday",
   "classStart": "6:45am",
   "classEnd": "7:45am",
   "teacher": "Netchem Hairston",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "className": "all levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "tuesday",
   "classStart": "12:00pm",
   "classEnd": "1:00pm",
   "teacher": "Ira Ruiz",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "className": "all levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "thursday",
   "classStart": "12:00pm",
   "classEnd": "1:00pm",
   "teacher": "Dhyana Masla",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "className": "all levels",
   "studio": "Bhakti Center",
   "coords": "40.723776,-73.9906827",
   "borough": "manhattan",
   "neighborhood": "East Village",
   "day": "sunday",
   "classStart": "10:00am",
   "classEnd": "11:00am",
   "teacher": "Syama Masla",
   "price": null,
   "scheduleLink": "http://bhakticenter.org/"
 },
 {
   "className": "liberation prison yoga community class",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "monday",
   "classStart": "4:00pm",
   "classEnd": "5:00pm",
   "teacher": "Onieka Mays",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "className": "mindful yoga for veterans (and everyone)",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "saturday",
   "classStart": "11:30am",
   "classEnd": "1:00pm",
   "teacher": "Madelaine Mayer",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "className": "community yoga",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "sunday",
   "classStart": "11:30am",
   "classEnd": "12:45pm",
   "teacher": "Stephen McManus",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "className": "yoga for 12 step recovery",
   "studio": "The Three Jewels Outreach Center",
   "coords": "40.7307518,-73.9924117",
   "borough": "manhattan",
   "neighborhood": "Greenwich Village",
   "day": "sunday",
   "classStart": "5:00pm",
   "classEnd": "6:30pm",
   "teacher": "Adina Saperstein",
   "price": null,
   "scheduleLink": "http://threejewels.org/classes-and-schedule/"
 },
 {
   "className": "power community $10",
   "studio": "Lyons Den Power Yoga",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Tribeca",
   "day": "sunday",
   "classStart": "7:00pm",
   "classEnd": "8:00pm",
   "teacher": "Aneta Bondarenko",
   "price": null,
   "scheduleLink": "http://lyonsdenpoweryoga.com/"
 },
 {
   "className": "win win donation class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "monday",
   "classStart": "7:30am",
   "classEnd": "8:30am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "className": "win win donation class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "7:30am",
   "classEnd": "8:30am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "className": "win win donation class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "wednesday",
   "classStart": "2:30pm",
   "classEnd": "3:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "className": "win win donation class",
   "studio": "Yoga 216",
   "coords": "40.718597,-74.0068966",
   "borough": "manhattan",
   "neighborhood": "Chelsea",
   "day": "sunday",
   "classStart": "10:15am",
   "classEnd": "11:15am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yoga216.com/schedule/"
 },
 {
   "className": "community class",
   "studio": "Mang'Oh Yoga",
   "coords": "40.747274,-73.9748507",
   "borough": "manhattan",
   "neighborhood": "Murray Hill",
   "day": "sunday",
   "classStart": "6:00pm",
   "classEnd": "7:15pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.mangohstudio.com/"
 },
 {
   "className": "30 minute meditation free",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "monday",
   "classStart": "1:30pm",
   "classEnd": "2:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "className": "donation community class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "monday",
   "classStart": "3:00pm",
   "classEnd": "4:00pm",
   "teacher": "Michelle Vanegas",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "className": "donation community class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "wednesday",
   "classStart": "3:00pm",
   "classEnd": "4:00pm",
   "teacher": "Amanda Reichert",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "className": "donation community class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "wednesday",
   "classStart": "8:30pm",
   "classEnd": "9:30pm",
   "teacher": "Kiara Contreras",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "className": "donation community class",
   "studio": "Sonic Yoga",
   "coords": "40.7657608,-73.9853652",
   "borough": "manhattan",
   "neighborhood": "Midtown",
   "day": "sunday",
   "classStart": "3:00pm",
   "classEnd": "4:00pm",
   "teacher": "Lee Ann Walton",
   "price": null,
   "scheduleLink": "https://sonicyoga.com/"
 },
 {
   "className": "slow flow community class",
   "studio": "House of Jai",
   "coords": "40.7701017,-73.9561812",
   "borough": "manhattan",
   "neighborhood": "Upper East Side",
   "day": "saturday",
   "classStart": "2:00pm",
   "classEnd": "3:15pm",
   "teacher": "Serra Saridereli",
   "price": null,
   "scheduleLink": "http://www.houseofjai.com/schedule.php"
 },
 {
   "className": "cc hot vinyasa",
   "studio": "Pure Yoga West",
   "coords": "40.781852,-73.9819977",
   "borough": "manhattan",
   "neighborhood": "Upper West Side",
   "day": "thursday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "Matt Goldmark",
   "price": null,
   "scheduleLink": "http://pureyoga.com/apps/mindbody/elements/listschedule.php"
 },
 {
   "className": "cc hot slow flow",
   "studio": "Pure Yoga East",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Upper East Side",
   "day": "thursday",
   "classStart": "2:30pm",
   "classEnd": "3:00pm",
   "teacher": "Irina Baysara",
   "price": null,
   "scheduleLink": "http://pureyoga.com/apps/mindbody/elements/listschedule.php"
 },
 {
   "className": "cc hot power (open)",
   "studio": "Pure Yoga West",
   "coords": "40.781852,-73.9819977",
   "borough": "manhattan",
   "neighborhood": "Upper West Side",
   "day": "sunday",
   "classStart": "1:00pm",
   "classEnd": "2:00pm",
   "teacher": "Holly Corey",
   "price": null,
   "scheduleLink": "http://pureyoga.com/apps/mindbody/elements/listschedule.php"
 },
 {
   "className": "community yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "monday",
   "classStart": "10:00am",
   "classEnd": "11:30am",
   "teacher": "Caitlyn Johansen",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "className": "morning meditation with open sky sangha",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "tuesday",
   "classStart": "8:00am",
   "classEnd": "9:00am",
   "teacher": "Giorgio Handman",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "className": "community yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "wednesday",
   "classStart": "5:45pm",
   "classEnd": "6:45pm",
   "teacher": "Matty Espino",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "className": "morning meditation with open sky sangha",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "8:00am",
   "classEnd": "9:00am",
   "teacher": "Giorgio Handman",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "className": "community yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "12:00pm",
   "classEnd": "1:15pm",
   "teacher": "Madeline Warriner",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "className": "community prenatal",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "friday",
   "classStart": "10:45pm",
   "classEnd": "12:15pm",
   "teacher": "Nyota Nayo",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "className": "community yoga",
   "studio": "Harlem Yoga Studio",
   "coords": "40.7788136,-73.9555111",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "sunday",
   "classStart": "3:30pm",
   "classEnd": "4:30pm",
   "teacher": "Lauren Solomon",
   "price": null,
   "scheduleLink": "http://harlemyogastudio.com/schedule/"
 },
 {
   "className": "donation-based class - asana/meditation",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "monday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "tuesday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "Andrea",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "wednesday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "Erica",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "Andrea",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "friday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "Erica",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "monday",
   "classStart": "1:00pm",
   "classEnd": "2:00pm",
   "teacher": "Kelley",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "tuesday",
   "classStart": "1:00pm",
   "classEnd": "2:00pm",
   "teacher": "Carole",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "wednesday",
   "classStart": "1:00pm",
   "classEnd": "2:00pm",
   "teacher": "Kelley",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "thursday",
   "classStart": "1:00pm",
   "classEnd": "2:00pm",
   "teacher": "Juan",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "friday",
   "classStart": "1:00pm",
   "classEnd": "2:00pm",
   "teacher": "Carole",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "saturday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "Juan",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "sunday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "Carole",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class - beginners",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "saturday",
   "classStart": "4:00pm",
   "classEnd": "5:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "donation-based class - beginners",
   "studio": "Brahman Yoga",
   "coords": "40.8164459,-73.9564369",
   "borough": "manhattan",
   "neighborhood": "Harlem",
   "day": "sunday",
   "classStart": "4:00pm",
   "classEnd": "5:00pm",
   "teacher": "Luis",
   "price": null,
   "scheduleLink": "http://www.brahmanyoganyc.com/schedule/"
 },
 {
   "className": "all level flow (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "monday",
   "classStart": "6:30pm",
   "classEnd": "7:45pm",
   "teacher": "Jen Devery",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "meditation (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "tuesday",
   "classStart": "1:30pm",
   "classEnd": "2:00pm",
   "teacher": "Stefanie Mihoulides",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "all level flow (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "tuesday",
   "classStart": "6:30pm",
   "classEnd": "7:45pm",
   "teacher": "Roque Rodriguez",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "all level flow (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "wednesday",
   "classStart": "8:00pm",
   "classEnd": "9:00pm",
   "teacher": "Julia Schonberg",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "all level flow (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "thursday",
   "classStart": "12:15pm",
   "classEnd": "1:20pm",
   "teacher": "Stefanie Mihoulides",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "meditation (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "thursday",
   "classStart": "1:30pm",
   "classEnd": "2:00pm",
   "teacher": "Stefanie Mihoulides",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "advanced flow (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "friday",
   "classStart": "10:00am",
   "classEnd": "11:15am",
   "teacher": "Ge Wang",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "advanced flow (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "saturday",
   "classStart": "2:00pm",
   "classEnd": "3:15pm",
   "teacher": "Michael Santaniello",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "all level flow (donation)",
   "studio": "Hosh Yoga",
   "coords": "40.7234821,-73.9547496",
   "borough": "brooklyn",
   "neighborhood": "Greenpoint",
   "day": "sunday",
   "classStart": "10:00am",
   "classEnd": "11:30am",
   "teacher": "Jessica Lum",
   "price": null,
   "scheduleLink": "http://www.hoshyoga.org/"
 },
 {
   "className": "lunchtime meditation",
   "studio": "Sangha Yoga Shala",
   "coords": "40.716954,-73.9639786",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "11:30am",
   "classEnd": "12:00pm",
   "teacher": "Alana Kessler",
   "price": null,
   "scheduleLink": "http://sanghayoganyc.com/yoga/"
 },
 {
   "className": "lunchtime meditation",
   "studio": "Sangha Yoga Shala",
   "coords": "40.716954,-73.9639786",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "12:30pm",
   "classEnd": "1:15pm",
   "teacher": "Alana Kessler",
   "price": null,
   "scheduleLink": "http://sanghayoganyc.com/yoga/"
 },
 {
   "className": "community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "monday",
   "classStart": "4:00pm",
   "classEnd": "5:30pm",
   "teacher": "Salvador",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "className": "community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "tuesday",
   "classStart": "4:00pm",
   "classEnd": "5:30pm",
   "teacher": "Gabe",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "className": "community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "thursday",
   "classStart": "4:00pm",
   "classEnd": "5:30pm",
   "teacher": "Sabina",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "className": "community $10",
   "studio": "Abhayasa Yoga Center",
   "coords": "40.714043,-73.9503747",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "friday",
   "classStart": "4:00pm",
   "classEnd": "5:30pm",
   "teacher": "Kirby",
   "price": null,
   "scheduleLink": "http://www.abhyasayogacenter.com/schedule"
 },
 {
   "className": "donation meditation",
   "studio": "Makara Studio",
   "coords": "40.7072587,-73.9450777",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "11:00am",
   "classEnd": "11:45pm",
   "teacher": "Conni Mallchock",
   "price": null,
   "scheduleLink": "http://makarastudio.com/classes"
 },
 {
   "className": "donation yoga open level",
   "studio": "Makara Studio",
   "coords": "40.7072587,-73.9450777",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "sunday",
   "classStart": "1:15pm",
   "classEnd": "2:45pm",
   "teacher": "Lola",
   "price": null,
   "scheduleLink": "http://makarastudio.com/classes"
 },
 {
   "className": "donation yoga open level",
   "studio": "Makara Studio",
   "coords": "40.7072587,-73.9450777",
   "borough": "brooklyn",
   "neighborhood": "Williamsburg",
   "day": "saturday",
   "classStart": "2:00pm",
   "classEnd": "3:15pm",
   "teacher": "Leyla",
   "price": null,
   "scheduleLink": "http://makarastudio.com/classes"
 },
 {
   "className": "community class ($5)",
   "studio": "Daya Yoga Studio",
   "coords": "40.705452,-73.9269326",
   "borough": "brooklyn",
   "neighborhood": "Bushwick",
   "day": "tuesdat",
   "classStart": "2:00pm",
   "classEnd": "3:15pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://dayayogastudio.com/"
 },
 {
   "className": "meditation (donation)",
   "studio": "Daya Yoga Studio",
   "coords": "40.705452,-73.9269326",
   "borough": "brooklyn",
   "neighborhood": "Bushwick",
   "day": "wednesday",
   "classStart": "9:15pm",
   "classEnd": "9:45am",
   "teacher": "Jen MacFarlane",
   "price": null,
   "scheduleLink": "http://dayayogastudio.com/"
 },
 {
   "className": "community class ($5)",
   "studio": "Daya Yoga Studio",
   "coords": "40.705452,-73.9269326",
   "borough": "brooklyn",
   "neighborhood": "Bushwick",
   "day": "thursday",
   "classStart": "2:00pm",
   "classEnd": "3:15pm",
   "teacher": "Michelle Miller",
   "price": null,
   "scheduleLink": "http://dayayogastudio.com/"
 },
 {
   "className": "community open level",
   "studio": "Ridgewood Yoga Studio",
   "coords": "40.6978022,-73.9084293",
   "borough": "queens",
   "neighborhood": "Ridgewood",
   "day": "thursday",
   "classStart": "10:00am",
   "classEnd": "11:00am",
   "teacher": "Nyota Nayo",
   "price": null,
   "scheduleLink": "http://ridgewoodyogastudio.com/"
 },
 {
   "className": "varies",
   "studio": "Brooklyn Yoga Collective",
   "coords": "40.671702,-73.9594637",
   "borough": "brooklyn",
   "neighborhood": "Crown Heights",
   "day": "monday - sunday",
   "classStart": "7:00am",
   "classEnd": "10:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://brooklynyogacollective.com/#calendar_anchor"
 },
 {
   "className": "community class",
   "studio": "Shambhala Yoga and Dance Center",
   "coords": "40.6774267,-73.9648663",
   "borough": "brooklyn",
   "neighborhood": "Prospect Heights",
   "day": "tuesday",
   "classStart": "1:45pm",
   "classEnd": "2:45pm",
   "teacher": "Sabine Jean-François",
   "price": null,
   "scheduleLink": "http://shambhalayogadance.com/schedule/"
 },
 {
   "className": "community class",
   "studio": "Shambhala Yoga and Dance Center",
   "coords": "40.6774267,-73.9648663",
   "borough": "brooklyn",
   "neighborhood": "Prospect Heights",
   "day": "wednesday",
   "classStart": "6:00am",
   "classEnd": "6:45am",
   "teacher": "Sarah Fishstrom",
   "price": null,
   "scheduleLink": "http://shambhalayogadance.com/schedule/"
 },
 {
   "className": "community class",
   "studio": "Shambhala Yoga and Dance Center",
   "coords": "40.6774267,-73.9648663",
   "borough": "brooklyn",
   "neighborhood": "Prospect Heights",
   "day": "thursday",
   "classStart": "1:45pm",
   "classEnd": "2:45pm",
   "teacher": "Shawna Wakefield",
   "price": null,
   "scheduleLink": "http://shambhalayogadance.com/schedule/"
 },
 {
   "className": "community class",
   "studio": "Area Yoga Brooklyn",
   "coords": "40.6815356,-73.9789979",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "sunday",
   "classStart": "8:15pm",
   "classEnd": "9:15pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.areayogabrooklyn.com/"
 },
 {
   "className": "varies ($10 min donation)",
   "studio": "Brooklyn Yoga School",
   "coords": "40.6798509,-73.9773543",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "monday - sunday",
   "classStart": "9:00am",
   "classEnd": "10:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.brooklynyogaschool.com/schedule/"
 },
 {
   "className": "open flow-pay what you can",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "wednesday",
   "classStart": "9:15am",
   "classEnd": "10:30am",
   "teacher": "Amy Quinn Suplina",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "className": "hour basics-pay what you can",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "thursday",
   "classStart": "12:30pm",
   "classEnd": "1:30pm",
   "teacher": "Cari Friedman",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "className": "hour basics-pay what you can",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "thursday",
   "classStart": "12:30pm",
   "classEnd": "1:30pm",
   "teacher": "Cari Friedman",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "className": "hour align-pay what you can ",
   "studio": "Bend and Bloom Yoga",
   "coords": "40.6773946,-73.9833665",
   "borough": "brooklyn",
   "neighborhood": "Park Slope",
   "day": "friday",
   "classStart": "5:00pm",
   "classEnd": "6:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.bendandbloom.com/class-schedule/"
 },
 {
   "className": "open by donation",
   "studio": "Third Root Community Health Center",
   "coords": "40.6413573,-73.9652507",
   "borough": "brooklyn",
   "neighborhood": "Kensington",
   "day": "wednesday",
   "classStart": "11:15am",
   "classEnd": "12:30pm",
   "teacher": "Shelly Nicole",
   "price": null,
   "scheduleLink": "http://www.secure-booker.com/thirdroot/classschedule/classschedule.aspx#"
 },
 {
   "className": "rising teacher's yoga",
   "studio": "Third Root Community Health Center",
   "coords": "40.6413573,-73.9652507",
   "borough": "brooklyn",
   "neighborhood": "Kensington",
   "day": "thursday",
   "classStart": "9:00am",
   "classEnd": "10:15am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.secure-booker.com/thirdroot/classschedule/classschedule.aspx#"
 },
 {
   "className": "open by donation",
   "studio": "Third Root Community Health Center",
   "coords": "40.6413573,-73.9652507",
   "borough": "brooklyn",
   "neighborhood": "Kensington",
   "day": "saturday",
   "classStart": "12:30pm",
   "classEnd": "1:45pm",
   "teacher": "Elizabeth Gonzalez",
   "price": null,
   "scheduleLink": "http://www.secure-booker.com/thirdroot/classschedule/classschedule.aspx#"
 },
 {
   "className": "vinyasa flow ($10)",
   "studio": "The Yoga Room",
   "coords": "40.7397922,-73.9358425",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "1:30pm",
   "classEnd": "2:45pm",
   "teacher": "Ellen",
   "price": null,
   "scheduleLink": "http://www.the-yoga-room.com/classes/yoga-classes/"
 },
 {
   "className": "vinyasa flow ($10)",
   "studio": "The Yoga Room",
   "coords": "40.7397922,-73.9358425",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "1:30pm",
   "classEnd": "2:30pm",
   "teacher": "Lauren",
   "price": null,
   "scheduleLink": "http://www.the-yoga-room.com/classes/yoga-classes/"
 },
 {
   "className": "vinyasa flow ($10)",
   "studio": "The Yoga Room",
   "coords": "40.7397922,-73.9358425",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "saturday",
   "classStart": "3:30pm",
   "classEnd": "4:45pm",
   "teacher": "Amanda",
   "price": null,
   "scheduleLink": "http://www.the-yoga-room.com/classes/yoga-classes/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "tuesday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "tuesday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "2:00pm",
   "classEnd": "3:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "yin yoga ($10)",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "8:30pm",
   "classEnd": "10:00pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "inversions flow level 3 ($10)",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "saturday",
   "classStart": "12:00pm",
   "classEnd": "1:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "saturday",
   "classStart": "8:00am",
   "classEnd": "9:15am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "open level vinyasa",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "sunday",
   "classStart": "8:00am",
   "classEnd": "9:15am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "vinyasa level 3 ($10)",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "sunday",
   "classStart": "12:00pm",
   "classEnd": "1:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "meditation",
   "studio": "Yoga Agora",
   "coords": "40.7500506,-73.9293839",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "sunday",
   "classStart": "8:30pm",
   "classEnd": "9:30pm",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://www.yogaagora.com/schedule/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053711",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "monday",
   "classStart": "6:30am",
   "classEnd": "8:00am",
   "teacher": "Alina Yuen",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053712",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "tuesday",
   "classStart": "6:30am",
   "classEnd": "8:00am",
   "teacher": "Alina Yuen",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053713",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "wednesday",
   "classStart": "6:30am",
   "classEnd": "8:00am",
   "teacher": "Jacqueline Montenegro",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053714",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "6:30am",
   "classEnd": "8:00am",
   "teacher": "Jacqueline Montenegro",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "yang/yin ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053715",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "friday",
   "classStart": "7:00am",
   "classEnd": "8:00am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "hot vinyasa ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053717",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "9:30am",
   "classEnd": "10:30am",
   "teacher": "TBD",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053718",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "12:00pm",
   "classEnd": "1:30pm",
   "teacher": "Chris Olstrom",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053719",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "4:30pm",
   "classEnd": "6:00pm",
   "teacher": "Frank King",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053720",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "6:30pm",
   "classEnd": "8:00pm",
   "teacher": "Joseph Encina",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 },
 {
   "className": "bikram's yoga ($10)",
   "studio": "Bikram Yoga Astoria Queens",
   "coords": "40.7606538,-73.9053721",
   "borough": "queens",
   "neighborhood": "Astoria",
   "day": "thursday",
   "classStart": "8:15pm",
   "classEnd": "9:45pm",
   "teacher": "Johanna Fausto",
   "price": null,
   "scheduleLink": "http://bikramyogaqueensny.com/"
 }
]